"""followers

Revision ID: 073911608d8d
Revises: 94511dff47da
Create Date: 2018-10-25 06:55:48.681974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073911608d8d'
down_revision = '94511dff47da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
